### ISSUE TITLE
Bazel patching for external repositories sometimes fails on GitHub Actions

### ISSUE THREAD

**Issue by commure-stabai** [bazelbuild/setup-bazelisk#5]
I have a Bazel project using Go and Gazelle that works fine for everyone locally. However, while trying to run a GitHub Actions workflow using the `bazelbuild/setup-bazelisk` task, we get some strange errors.

We have an external dependency that's a non-Bazel `go_repository` dependency created by Gazelle (autogenerated BUILD files). Because autogeneration doesn't work quite right, we added a patch:
```bazel
go_repository(
    name = "com_github_go_kratos_grpc_gateway_v2",
    importpath = "github.com/go-kratos/grpc-gateway/v2",
    patch_args = ["-p1"],
    patches = ["//:tools/bazel/patches/com_github_go_kratos_grpc_gateway_v2.patch"],
    sum = "h1:jPqlxMJEoi8Yv4WIAhQNKczdKjADox8WKrTp3bJNjFM=",
    version = "v2.5.1-0.20210811062259-c92d36e434b1",
)
```

And here is the GitHub Actions config yaml:
```yaml
name: presubmit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - name: Build and test all libraries
        run: bazel test //libraries/...
      - name: Build and test all services
        run: bazel test //services/...
```

Again, these bazel commands work fine locally. But in a GitHub Actions run, it gives this error:
```
ERROR: An error occurred during the fetch of repository 'com_github_go_kratos_grpc_gateway_v2':
   Traceback (most recent call last):
	File "/home/runner/.cache/bazel/_bazel_runner/e6f8924385b8d99d80af96a4f412d3d0/external/bazel_gazelle/internal/go_repository.bzl", line 212, column 10, in _go_repository_impl
		patch(ctx)
	File "/home/runner/.cache/bazel/_bazel_runner/e6f8924385b8d99d80af96a4f412d3d0/external/bazel_gazelle/internal/go_repository.bzl", line 310, column 17, in patch
		fail("Error applying patch %s:\n%s%s" %
Error in fail: Error applying patch //:tools/bazel/patches/com_github_go_kratos_grpc_gateway_v2.patch:
patching file internal/httprule/BUILD.bazel
patching file protoc-gen-openapiv2/generator/BUILD.bazel
patching file protoc-gen-openapiv2/options/BUILD.bazel
patching file protoc-gen-openapiv2/options/annotations.proto
patching file protoc-gen-openapiv2/options/annotations.swagger.json
patching file protoc-gen-openapiv2/options/openapiv2.proto
patching file protoc-gen-openapiv2/options/openapiv2.swagger.json
The next patch would delete the file utilities/BUILD.bazel,
which does not exist!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
The next patch would delete the file utilities/doc.go,
which does not exist!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
The next patch would delete the file utilities/pattern.go,
which does not exist!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
The next patch would delete the file utilities/readerfactory.go,
which does not exist!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
The next patch would delete the file utilities/trie.go,
which does not exist!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
The next patch would delete the file utilities/trie_test.go,
which does not exist!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
```

Cloning the repo and applying the patch locally also works fine:
```
git clone https://github.com/go-kratos/grpc-gateway.git
cd grpc-gateway
patch -p1 -i patches/com_github_go_kratos_grpc_gateway_v2.patch
```
